### ISSUE TITLE
Project directory structure

### ISSUE THREAD

**Issue by MichaelrMentele** [zlw5009/pair-up#21]
Project skeleton

**Comment by MichaelrMentele** [comment]
Project structure created. Added click through links and stub code.

**Comment by zlw5009** [comment]
I like the structure. I'm not sure how I feel about the differences in application and session controllers. Splash page should probably be in an application views folder instead of sessions. I can see why it is in sessions though as if a user was logged in per session, they would be redirected to their dashboard. Perhaps the home page is within the sessions controller as that'll dictate whether or not the user is redirected to their dashboard or the landing page.

**Comment by MichaelrMentele** [comment]
The ApplicationController is a generic controller that has common methods for all following resource controllers to inherit from. It wouldn't have any views. The splash page is where you login send a POST request to create a new session. The sessions controller isn't a parent and it only covers creation and destruction of a session. We don't have to do it that way but this is the convention for RESTful routes and a pattern advocated by Launchschool.

**Comment by zlw5009** [comment]
Well technically, the splash page won't be incorporated in any sessions and is primarily used as a informative page with links to sign up/ login. At those pages, sessions will be created.

**Comment by MichaelrMentele** [comment]
Hey, I misunderstood your point. I think you are right about moving the view. As for the other issue, I forgot we aren't using class based controllers. I'd like to keep the app.rb namespace to not have route logic. I personally like to keep my different files at consistent levels of abstraction. Let's chat about this at our meeting today.
